### ISSUE TITLE
Use AbracaDABra's library instead

### ISSUE THREAD

**Issue by andimik** [Lamarqe/mpdcast-dab#2]
With the **appImage** I tried to use `mpdcast-dab` but the results are much behind my expectations and I may get in the error (even for local stations >30 dB): 

![grafik](https://github.com/user-attachments/assets/ab4f65f5-0fa5-4be9-91e8-f2aae3a7ea5c)

> loading failed

Furthermore, it will not detect all muxes in my case.

As I am also not satisfied with the performance of `welle-io` (where I was contributing to some time ago) do you see any chance to switch to the library of https://github.com/kejpi/AbracaDABra ?

**Comment by Lamarqe** [comment]
I cannot find any source code for libdabsdr and I would not implement against a binary with unknown implementation.

**Comment by Lamarqe** [comment]
I believe by now that Abracadaba uses https://github.com/kwanty/sdrdab and the maintainer has most likely used this library as base for his application, keeping his contributions secret.

There were attempts to migrate welle.io to this library. However, the version which is publically available has its weaknesses. See the discussion here:
https://github.com/AlbrechtL/welle.io/issues/102

So also from that regard, it appears unrealistic that a switch to this backend is an easy win.
