### ISSUE TITLE
Use channel names in scan

### ISSUE THREAD

**Issue by andimik** [Lamarqe/mpdcast-dab#3]
Let me propose to write the current scanned channel name (e.g. `6A`) as well to the  progress bar (xx of 54 channels).

![grafik](https://github.com/user-attachments/assets/5cfe25e2-9853-45fd-9ba3-d2c0f294d167)

This is easier to understand for DAB users in my opinion ...

**Comment by Lamarqe** [comment]
Implemented as requested with https://github.com/Lamarqe/mpdcast-dab/commit/999c757c1667971e50a5481972552c936d1e3a19.
