### ISSUE TITLE
Wrong directory mentioned

### ISSUE THREAD

**Issue by andimik** [Lamarqe/mpdcast-dab#4]
https://github.com/Lamarqe/mpdcast-dab/blob/648fd9ba8c413f2701db78b392916501a223d7a5/README.md?plain=1#L130

in this line there is `cd mpdcast-dab` missing. For newbies, it might not so trivial as you think.

**Comment by Lamarqe** [comment]
Fixed with https://github.com/Lamarqe/mpdcast-dab/commit/bb8491ce134e3d19196dfd733ca99320fad2b5f2.
