### ISSUE TITLE
Missing sudo in readme

### ISSUE THREAD

**Issue by andimik** [Lamarqe/mpdcast-dab#6]
https://github.com/Lamarqe/mpdcast-dab/blob/648fd9ba8c413f2701db78b392916501a223d7a5/README.md?plain=1#L28-L30

All the lines shall be executed as `sudo`

**Comment by Lamarqe** [comment]
Fixed with https://github.com/Lamarqe/mpdcast-dab/commit/d6bb92c70aa34f54435a1d83865a86147fd67ae6.
