### ISSUE TITLE
(Ubuntu 24.04/PPA): NameError: name 'DabServer' is not defined

### ISSUE THREAD

**Issue by nRaecheR** [Lamarqe/mpdcast-dab#7]
First of all, thank you for this interesting project. 

I try to install the server from the provided PPA in an Ubuntu 24.04 AMD64 Podman image, startup parameters are adapted from the SystemD service file. The installation runs as expected but when I try to start the server I get the following output:

> Traceback (most recent call last):
  File "/usr/bin/mpdcast_dab", line 5, in <module>
    from mpdcast_dab.__main__ import main
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/__main__.py", line 88, in <module>
    def prepare_dab(options: dict[str, Any], web_app: web.Application, prefix: str) -> DabServer | None:
                                                                                       ^^^^^^^^^
NameError: name 'DabServer' is not defined

Could you give a hint what is wrong with my installation?

**Comment by Lamarqe** [comment]
> startup parameters are adapted from the SystemD service file

Please provide the details how you start the service / app. Then we might find the problem.
I wonder, why you don't start the service in the regular way.

**Comment by nRaecheR** [comment]
Here's the simple Dockerfile with the installation and startup:


```
FROM ubuntu:24.04

RUN set -xe \
    && apt update \
    && apt install -y software-properties-common \
    && add-apt-repository ppa:lamarqe/ppa \
    && apt update \
    && apt install -y mpdcast-dab \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/mpdcast_dab"]
CMD ["--conf /etc/mpd.conf"]

```

It follows the steps from the installation instructions. The mpd.conf has been mapped to the container and is the default one from the readme file (without bitrate setting)

**Comment by Lamarqe** [comment]
I suspect that there is a problem with initializing the Dab library.
I made a mistake with commit https://github.com/Lamarqe/mpdcast-dab/commit/fb30052e3959d20f7bd14ad69512cd87990abfce. It broke the lazy load of the Dab library.
I corrected it with https://github.com/Lamarqe/mpdcast-dab/commit/2bf329b35be56978027ac31112fa0f1c98b2b6a2.

Having that fixed, you should see the proper error message when loading the Dab lib.

**Comment by nRaecheR** [comment]
Yes, thank you. Using the new version fixes this problem. There's still a dependency problem, I will do a PR for that.
