### ISSUE TITLE
[FEATURE] Re-add support for Airspy and Soapysdr

### ISSUE THREAD

**Issue by nRaecheR** [Lamarqe/mpdcast-dab#9]
It would be great it re-add the support for devices like:

* Airspy
* SoapySDR

As the software is based on Welle.io which supports these devices out-of-the-box it shouldn't be to difficult to support these devices too.

**Comment by Lamarqe** [comment]
Defintitely possible, but currently not planned, as this is a one person project and I do not have any test environments for these.

**Comment by nRaecheR** [comment]
Yes, that's a shame that the support for these SDRs has been removed in the fork, it is available in the original project and works well. 

Since I only have spare Airspy sticks for these project myself, I can gladly help with testing. Without the support, the project is unfortunately not usable for me.
